version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: ../chat-example
      dockerfile: docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "${DOCKER_PREFIX}-app"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    user: "root"
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-server"
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #Redis Service
  redis:
    image: redis
    container_name: "${DOCKER_PREFIX}-redis"
    ports:
    - "6379:6379"
    expose:
      - 6379
    networks:
      - app-network

  #Node Service
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./node:/usr/app
    container_name: "${DOCKER_PREFIX}-node"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
